[build]
  base = "backend"
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  # Point to the folder relative to the 'base'
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
  force = true