[build]
  base = "backend"
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
  force = true