[build]
  base = "backend"
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  # We are telling Netlify EXACTLY where the file is
  directory = "." 
  included_files = ["main.py"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
  force = true